use_default_settings: true

server:
  port: 8080
  bind_address: 0.0.0.0
  secret_key: ${SEARXNG_SERVER_SECRET_KEY}
  image_proxy: true

general:
  debug: false

search:
  safe_search: 0
  autocomplete: google
  formats:
    - html
    - json
engines:
  - name: google
    disabled: true

  - name: duckduckgo
    disabled: true

  - name: bing
    disabled: true

  - name: brave
    disabled: true

  - name: ahmia
    disabled: true

  - name: torch
    disabled: true
